package com.csj.cn.whr.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activity
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Activity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   活动标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   活动内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   组织者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.organizer
     *
     * @mbg.generated
     */
    private String organizer;

    /**
     * Database Column Remarks:
     *   活动城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   举办地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   活动人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_number
     *
     * @mbg.generated
     */
    private Integer activityNumber;

    /**
     * Database Column Remarks:
     *   活动图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_imgUrl
     *
     * @mbg.generated
     */
    private String activityImgurl;

    /**
     * Database Column Remarks:
     *   活动开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startTime;

    /**
     * Database Column Remarks:
     *   活动结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.content
     *
     * @return the value of activity.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.content
     *
     * @param content the value for activity.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.organizer
     *
     * @return the value of activity.organizer
     *
     * @mbg.generated
     */
    public String getOrganizer() {
        return organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.organizer
     *
     * @param organizer the value for activity.organizer
     *
     * @mbg.generated
     */
    public void setOrganizer(String organizer) {
        this.organizer = organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.city
     *
     * @return the value of activity.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.city
     *
     * @param city the value for activity.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.address
     *
     * @return the value of activity.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.address
     *
     * @param address the value for activity.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_number
     *
     * @return the value of activity.activity_number
     *
     * @mbg.generated
     */
    public Integer getActivityNumber() {
        return activityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_number
     *
     * @param activityNumber the value for activity.activity_number
     *
     * @mbg.generated
     */
    public void setActivityNumber(Integer activityNumber) {
        this.activityNumber = activityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_imgUrl
     *
     * @return the value of activity.activity_imgUrl
     *
     * @mbg.generated
     */
    public String getActivityImgurl() {
        return activityImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_imgUrl
     *
     * @param activityImgurl the value for activity.activity_imgUrl
     *
     * @mbg.generated
     */
    public void setActivityImgurl(String activityImgurl) {
        this.activityImgurl = activityImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}