package com.csj.cn.whr.dto;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.metadata.BaseRowModel;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table employee
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Employee extends BaseRowModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.job_number
     *
     * @mbg.generated
     */
    private Long jobNumber;

    /**
     * Database Column Remarks:
     *   性别1:男,2:女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     * Database Column Remarks:
     *   身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     * Database Column Remarks:
     *   婚姻状况(0：未婚，1：已婚)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.is_married
     *
     * @mbg.generated
     */
    private Integer isMarried;

    /**
     * Database Column Remarks:
     *   民族
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.nation_id
     *
     * @mbg.generated
     */
    private Integer nationId;

    /**
     * Database Column Remarks:
     *   籍贯
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hometown
     *
     * @mbg.generated
     */
    private String hometown;

    /**
     * Database Column Remarks:
     *   政治面貌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.political_id
     *
     * @mbg.generated
     */
    private Integer politicalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   所属部门
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     * Database Column Remarks:
     *   职位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position_id
     *
     * @mbg.generated
     */
    private Integer positionId;

    /**
     * Database Column Remarks:
     *   职称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.job_title
     *
     * @mbg.generated
     */
    private Integer jobTitle;

    /**
     * Database Column Remarks:
     *   聘用形式(1：劳动合同；2：劳务合同）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employment_form
     *
     * @mbg.generated
     */
    private Integer employmentForm;

    /**
     * Database Column Remarks:
     *   入职日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.entry_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.job_number
     *
     * @return the value of employee.job_number
     *
     * @mbg.generated
     */
    public Long getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.job_number
     *
     * @param jobNumber the value for employee.job_number
     *
     * @mbg.generated
     */
    public void setJobNumber(Long jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.identity
     *
     * @return the value of employee.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.identity
     *
     * @param identity the value for employee.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.is_married
     *
     * @return the value of employee.is_married
     *
     * @mbg.generated
     */
    public Integer getIsMarried() {
        return isMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.is_married
     *
     * @param isMarried the value for employee.is_married
     *
     * @mbg.generated
     */
    public void setIsMarried(Integer isMarried) {
        this.isMarried = isMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.nation_id
     *
     * @return the value of employee.nation_id
     *
     * @mbg.generated
     */
    public Integer getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.nation_id
     *
     * @param nationId the value for employee.nation_id
     *
     * @mbg.generated
     */
    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hometown
     *
     * @return the value of employee.hometown
     *
     * @mbg.generated
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hometown
     *
     * @param hometown the value for employee.hometown
     *
     * @mbg.generated
     */
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.political_id
     *
     * @return the value of employee.political_id
     *
     * @mbg.generated
     */
    public Integer getPoliticalId() {
        return politicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.political_id
     *
     * @param politicalId the value for employee.political_id
     *
     * @mbg.generated
     */
    public void setPoliticalId(Integer politicalId) {
        this.politicalId = politicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department_id
     *
     * @return the value of employee.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department_id
     *
     * @param departmentId the value for employee.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position_id
     *
     * @return the value of employee.position_id
     *
     * @mbg.generated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position_id
     *
     * @param positionId the value for employee.position_id
     *
     * @mbg.generated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.job_title
     *
     * @return the value of employee.job_title
     *
     * @mbg.generated
     */
    public Integer getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.job_title
     *
     * @param jobTitle the value for employee.job_title
     *
     * @mbg.generated
     */
    public void setJobTitle(Integer jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employment_form
     *
     * @return the value of employee.employment_form
     *
     * @mbg.generated
     */
    public Integer getEmploymentForm() {
        return employmentForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employment_form
     *
     * @param employmentForm the value for employee.employment_form
     *
     * @mbg.generated
     */
    public void setEmploymentForm(Integer employmentForm) {
        this.employmentForm = employmentForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.entry_date
     *
     * @return the value of employee.entry_date
     *
     * @mbg.generated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.entry_date
     *
     * @param entryDate the value for employee.entry_date
     *
     * @mbg.generated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}